# Puerto del servidor
server.port=8080

# Nombre de la aplicación
spring.application.name=backend

# Configuración de subida de imágenes
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Ruta de los archivos JSON
data.path=data/

# Ruta de las imágenes
images.path=data/imagenes/

# Configuración de Mailtrap
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=MAILTRAP_USERNAME
spring.mail.password=MAILTRAP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuración de JWT
jwt.secret=lobby-one-secret-key-2026-ingenieria-software
jwt.expiration=86400000
